VERSION --global-cache 0.7

IMPORT ../../ AS elixir

build:
    # see https://hexdocs.pm/phoenix/1.7.10/releases.html#containers for an example build container
    ARG ELIXIR_VERSION=1.15.4
    ARG OTP_VERSION=26.0.2
    ARG DEBIAN_VERSION=bullseye-20230612
    FROM hexpm/elixir:$ELIXIR_VERSION-erlang-$OTP_VERSION-debian-$DEBIAN_VERSION
    RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ca-certificates \
    build-essential \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*
    WORKDIR /app
    DO elixir+INIT
    DO elixir+MIX --command="do local.rebar --force, local.hex --force"
    # oban is commonly used in the elixir community and we use it
    # i'm not sure how to pass secrets and then wrap this command using the MIX function
    # it would be nice to be able to optionally include it because it's so widely used
    # RUN --secret OBAN_KEY_FINGERPRINT \
    #     --secret OBAN_LICENSE_KEY \
    #     mix hex.repo add oban https://getoban.pro/repo \
    #         --fetch-public-key $OBAN_KEY_FINGERPRINT \
    #         --auth-key $OBAN_LICENSE_KEY
    # deps should be cached and added incrementally as new deps are added to `mix.exs`
    COPY mix.exs mix.lock ./
    DO elixir+MIX --command="deps.get"
    # deps should be compiled only when necessary
    # technically you should only pull the relevant environment config.exs in (e.g. dev.exs for MIX_ENV=dev)
    COPY --if-exists --dir config ./
    DO elixir+MIX --command="deps.compile"
    COPY --dir lib ./
    # the application _could_ be compiled incrementally but it does introduce some level of flakiness so a command like `mix clean` is recommended
    # to prevent that. alternatively you could allow incremental app compilation but have an escape hatch to do a full recompile
    DO elixir+MIX --command="clean"
    DO elixir+MIX --command="compile"

ex-unit:
    FROM +build
    DO elixir+MIX --command="test"

dialyzer:
    FROM +build
    # plts can be stored in _build or in custom directories
    # see https://hexdocs.pm/dialyxir/readme.html
    COPY --if-exists .dialyzer_ignore.exs ./
    DO elixir+MIX --command="dialyzer" --MIX_ENV=test

test:
    BUILD +ex-unit
    BUILD +dialyzer