# used by earthly
version: "3"

services:
  phoenix_app:
    container_name: phoenix_app
    image: phoenix_app:latest
    restart: unless-stopped
    # keep the container running forever
    command: sh -c "sleep infinity"
    networks:
      - internal
    environment:
      - POSTGRES_SERVICE_HOST=db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal

networks:
  internal:
    internal: true
