VERSION --global-cache 0.7

IMPORT ../../ AS elixir

build:
    ARG ELIXIR_VERSION=1.15.4
    ARG OTP_VERSION=26.0.2
    ARG DEBIAN_VERSION=bullseye-20230612
    FROM hexpm/elixir:$ELIXIR_VERSION-erlang-$OTP_VERSION-debian-$DEBIAN_VERSION
    RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ca-certificates \
    build-essential \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*
    WORKDIR /app
    DO elixir+INIT
    DO elixir+MIX --command="do local.rebar --force, local.hex --force"
    COPY mix.exs mix.lock ./
    DO elixir+MIX --command="deps.get"
    COPY --if-exists --dir config ./
    DO elixir+MIX --command="deps.compile"
    COPY --dir priv lib ./
    DO elixir+MIX --command="clean"
    DO elixir+MIX --command="compile"

ex-unit-setup:
    FROM +build
    COPY --dir test ./
    ENTRYPOINT ["mix", "test"]
    SAVE IMAGE test:latest

ex-unit:
  FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
  WORKDIR /test
  COPY docker-compose.yml ./
  DO elixir+INIT
  WITH DOCKER \
        --load tests:latest=+ex-unit-setup \
        --compose docker-compose.yml \
        --service db
    RUN --mount=type=cache,mode=0777,id=$EARTHLY_ELIXIR_DEPS_CACHE_ID,sharing=locked,target=deps \
        --mount=type=cache,mode=0777,id=$EARTHLY_ELIXIR_BUILD_CACHE_ID,sharing=locked,target=_build \
      docker run \
      --mount type=bind,source="$(pwd)"/deps,target=/app/deps \
      --mount type=bind,source="$(pwd)"/_build,target=/app/_build \
      --network=default_internal \
      --env DBHOST=db \
      tests:latest
  END

test:
    BUILD +ex-unit